### ISSUE TITLE
catch without 

### ISSUE THREAD

**Issue by arnold-graf** [sindresorhus/is-installed-globally#12]
the `error` in `…} catch (error) {…` is _not_ optional in ECMAScript. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch. Used in https://github.com/sindresorhus/is-installed-globally/blob/6be89e62be8a4930aa902130e782d0bc66750ee3/index.js#L12; This trips up some recent node versions.

**Comment by sindresorhus** [comment]
It is optional in the Node.js versions this package targets.
