### ISSUE TITLE
Make it a function?

### ISSUE THREAD

**Issue by tunnckoCore** [sindresorhus/is-installed-globally#5]
So it can be used to check is given module installed globally.
I just happened to look around my old issues and found https://github.com/tunnckoCoreLabs/get-installed-path/issues/22#issuecomment-435577820 where it seems I made a function that is named like this package, haha. :laughing: 

I created a few libs around that before few years.

- https://github.com/tunnckoCoreLabs/get-installed-path
- https://github.com/tunnckoCore/detect-installed
- https://github.com/tunnckoCore/is-installed

I'm actually okay with the `is-installed` one. So we can just link it here :)
I'm going to update them and move them to my monorepo these days.

**Comment by sindresorhus** [comment]
I'm not clear on what the benefit of making it a function is?
