### ISSUE TITLE
Fails on Windows

### ISSUE THREAD

**Issue by ilg-ul** [sindresorhus/is-installed-globally#6]
I initially used version 0.1.0 and everything was fine, but after upgrading to higher versions, on Windows the module fails with a message like

```
test/tap/020-checker.js ............................. 34/35
  outdated version untuned
  not ok ENOENT: no such file or directory, lstat 'C:\Users\ilg\AppData\Roaming\npm\node_modules'
    stack: >
      Error:
          Object.<anonymous> (node_modules/is-installed-globally/index.js:8:29)
          Object.Module._compile (node_modules/source-map-support/source-map-support.js:541:25)
    errno: -4058
    syscall: lstat
    code: ENOENT
    path: C:\Users\ilg\AppData\Roaming\npm\node_modules
    tapCaught: returnedPromiseRejection
    test: outdated version untuned

total ............................................... 40/42
```

The problem was introduced since 0.2.0.

It would probably be useful to run CI not only on Linux, but on Windows too (I use AppVeyor, but I think Travis also added support for Windows).

**Comment by sindresorhus** [comment]
// @vladimyr

**Comment by vladimyr** [comment]
I'm afraid I can't help you with this one. I don't use Windows and don't have any Win machine to test on. Best thing I could do is to boot a vm but that's kinda unreliable. :man_shrugging:

**Comment by ilg-ul** [comment]
> boot a vm but that's kinda unreliable.

If you install the official Microsoft Windows 10 ISO in a VirtualBox machine, it is quite reliable, I have two Windows VMs (32/64-bit), plus several 32/64-bit Linux VMs (I'm on Mac) and this is how I test my modules on all platforms; Windows 10 will complain about the missing activation, but for occasional tests it is ok.

Once you fix the problem, you can add a set of CI Windows tests, for example in the project using your module I have the following AppVeyor configuration file:

https://github.com/xpack/update-checker-js/blob/master/.appveyor.yml

**Comment by ilg-ul** [comment]
BTW, you problem seems related to the weird Windows paths.

And most probably is inherited from the dependencies (global-dirs?)
